# Generated by Django 6.0 on 2025-12-03 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['name', 'sku'], name='inventory_d_name_8ffcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['quantity_in_stock'], name='inventory_d_quantit_5a9def_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['drug', 'transaction_type'], name='inventory_s_drug_id_4e690f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['-created_at'], name='inventory_s_created_b62db6_idx'),
        ),
    ]
